# RBAC: даёт подам GitLab Runner (в namespace gitlab-runner) право
# применять манифесты в namespace default (деплой psapp).
# Применить: kubectl apply -f gitlab-runner/rbac-deploy.yaml
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: gitlab-runner-deploy
  namespace: default
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["services", "pods", "configmaps"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gitlab-runner-deploy
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: gitlab-runner-deploy
subjects:
  - kind: ServiceAccount
    name: default
    namespace: gitlab-runner
